### PR TITLE
fix: issue #72

### PR DESCRIPTION
**Pull request by yoution**
@maxceem please review

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution So far there are 2 issues mentioned in the comments https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/72#issuecomment-884111312

1. Don't include `workPeriods.isFirstWeek` and `workPeriods.isLastWeek` into the `fields` because there are no such fields. We can only filter by these params.

2. `&billingAccountId=0` is included twice inside the request which is converted to array in the API side. `&billingAccountId=0` should be included only once in URL.

**Comment by yoution** [comment]
@maxceem https://github.com/topcoder-platform/micro-frontends-taas-admin-app/blob/dev/src/services/workPeriods.js#L104
the `buildRequestQuery` is a little disgusting， it will add two `billingAccountId`, and will remove `workPeriods.isFirstWeek and workPeriods.isLastWeek` if I not put them in `fields`

**Comment by maxceem** [comment]
@yoution feel free to update it as needed to support our new case.

**Review by maxceem — APPROVED** [review]
@yoution works great! Merging to pass it for QA.

**Pull request merged**
