### PR TITLE
fix: issue #73

### PR DESCRIPTION
**Pull request by yoution**
@maxceem please review

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
thanks, @yoution works good.

Can we also disable the "select all" checkbox and show the same tooltip for it https://monosnap.com/file/NtZf9qGKTOkzEMAKCT8wGLL5IycyiG

There was also a requirement to show a tooltip for the disabled "Process Payment" button, but we can cancel that requirement.

**Comment by yoution** [comment]
@maxceem can we just disable the checkbox, and not show the tooltip?
in another case， there are two rows, if first row is disabled by reason A, second row is disabled by B, how to show the tooltip?
reason A + B?

**Comment by maxceem** [comment]
@yoution For rows you did it in a good way. 2 reasons are displayed, it's nice.

For the checkbox I still prefer to have a tooltip so it is clear for the user why it's disabled. It should not be hard to add a Tooltip to the checkbox, see how we add it inside rows https://github.com/topcoder-platform/micro-frontends-taas-admin-app/blob/dev/src/routes/WorkPeriods/components/PeriodItem/index.jsx#L142-L158

For this "select all" checkox, there would be always only one reason. No need to implement multiple reasons like inside rows.

**Comment by yoution** [comment]
ok, I will add two reasons

**Comment by maxceem** [comment]
> ok, I will add two reasons

hmm, @yoution this is already done, no need to add two reasons, see. This already works automatically inside rows:

image

Only one thing is needed:
- disable "select all" checkox
- show tooltip for disabled select all checkbox 
- only ONE reason in the tooltip for "select all" checkox

Sorry if I confuse you, feel free to contact me on Slack if you like to have a quick discussion.

**Pull request closed without merging**
